version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: patients_directory
      POSTGRES_PASSWORD: test123
    ports:
      - 5432:5432
    volumes:
      - ./.data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
